name: 'Install BaseX'
description: 'Install BaseX on a GitHub Actions runner, assumes Java already installed'
inputs:
  basex-version:
    description: 'The version of BaseX to install (e.g., 11.7)'
    required: true
    default: '11.7'
runs:
  using: 'composite'
  steps:
    - name: Download BaseX
      shell: bash
      run: |
        BASEX_VERSION="${{ inputs.basex-version }}"
        BASEX_CLEAN_VERSION="${BASEX_VERSION//./}"
        wget https://files.basex.org/releases/$BASEX_VERSION/BaseX$BASEX_CLEAN_VERSION.zip -O BaseX.zip

    - name: Unzip BaseX
      shell:  "bash"
      run: |
        unzip BaseX.zip -d $HOME      
        rm BaseX.zip

    - name: Add BaseX to PATH
      shell: "bash"
      run: |
          echo "BASEX_ROOT=$HOME/basex" >> $GITHUB_ENV 
          echo "PATH=$PATH:$HOME/basex/bin" >> $GITHUB_ENV

    - name: Verify BaseX installation
      shell: "bash"
      run: |
          basex -v"