name: Run BaseX Tests

on:
  workflow_dispatch: # Enables manual trigger
  push:
    branches:
      - main
    paths:
      - '.gitea/workflows/trigger/release'

  
jobs:
  test:
    runs-on:  ghcr.io/quodatum/basexhttp:basex-10.7

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run BaseX Tests
      run:  'basex/bin/basex -t .'