%%{init: {'securityLevel': 'loose', 'theme':'base'}}%%    
classDiagram
direction TB

 class RESTXQ:::cssRest { }
 class INVOKE:::cssMain { }
 class TEST { }

class pdfbox { << Pdfbox3.xqm >>}


link pdfbox "modules/F000001/index.html" "This is a tooltip for org.expkg_zone58.Pdfbox3" 

