name: Run BaseX Tests

on:
  workflow_dispatch: # Enables manual trigger
  push:
    branches:
      - main
    paths:
      - ".gitea/workflows/trigger/release"
  
 
jobs:
 
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        basex-version: ["10.7", "11.7"]
      
    steps:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install BaseX
        uses: ./.github/actions/install-basex
        with:
          basex-version: ${{ matrix.basex-version }}  # Specify the BaseX version here    
     
      - name: Build package
        run: |
          basex scripts/make-xar.xq
          basex scripts/repo-install.xq

      - name: Run tests
        run: |
          basex -Wt tests
